### PR TITLE
Add discord-extension

### PR DESCRIPTION
**Pull request by aislandener**

### CODE REVIEW

**Comment by rivafarabi** [comment]
Can you add an .asar file in your repository releases? 
You can build it by running `deckboard-kit --build` or `npm run build` in repository folder.

**Comment by aislandener** [comment]
Hi, I had made the release but it was in the draft, I made the release of
the version now, sorry for the inconvenience.

Em dom, 13 de fev de 2022 14:36, Riva Farabi ***@***.***>
escreveu:

**Comment by aislandener** [comment]
Hi, I had made the release but it was in the draft, I made the release of the version now, sorry for the inconvenience

**Comment by aislandener** [comment]
adjustments made to suit the design

**Pull request merged**
